Repository viruskizz/42bangkok-miniRT, pull requests merged in 2023-03, with the labels that each got.

#4 Feature/plan obj
  files/basic.rt
  includes/data.h
  includes/minirt.h
  includes/utils.h
  srcs/camera.c
  srcs/light.c
  srcs/obj/obj.c
  srcs/obj/plane.c
  srcs/obj/scene.c
  srcs/obj/sphere.c
  srcs/render.c
  srcs/utils/color.c
  srcs/utils/pixel.c
  srcs/utils/unit.c
  srcs/utils/vector2.c
Labels: Feature

#6 Feature/norminette sphere,plane
  includes/data.h
  includes/minirt.h
  includes/utils.h
  srcs/camera.c
  srcs/exit.c
  srcs/light.c
  srcs/main.c
  srcs/obj/cylinder.c
  srcs/obj/obj.c
  srcs/obj/plane.c
  srcs/obj/scene.c
  srcs/obj/sphere.c
  srcs/render.c
  srcs/setup.c
  srcs/transform/trans.c
  srcs/transform/trans_homo.c
  srcs/transform/trans_rot.c
  srcs/utils/color.c
  srcs/utils/converting_value.c
  srcs/utils/function_utils1.c
  srcs/utils/function_utils2.c
  srcs/utils/matrix1.c
  srcs/utils/matrix2.c
  srcs/utils/pixel.c
  srcs/utils/unit.c
  srcs/utils/vector1.c
  srcs/utils/vector2.c
Labels: norminette

#9 Feature/parsing and key
  files/basic.rt
  includes/data.h
  includes/key.h
  includes/minirt.h
  srcs/camera.c
  srcs/debug/print_tdata.c
  srcs/debug/print_utils.c
  srcs/event/camera_key_transformation.c
  srcs/event/input_keyhandler.c
  srcs/event/light_key_transformation.c
  srcs/event/plane_key_transformation.c
  srcs/event/sphere_key_transfromation.c
  srcs/interface/elements_interface1.c
  srcs/interface/elements_interface2.c
  srcs/interface/selection_interface.c
  srcs/interface/template_interface.c
  srcs/interface/window_interface.c
  srcs/light.c
  srcs/main.c
  srcs/obj/cylinder.c
  srcs/obj/obj.c
  srcs/obj/plane.c
  srcs/obj/scene.c
  srcs/obj/sphere.c
  srcs/parsing/parsing_input.c
  srcs/render.c
  srcs/utils/function_utils2.c
Labels: Feature

#13 fix: panel-ui
  includes/data.h
  includes/minirt.h
  srcs/event/camera_key_transformation.c
  srcs/event/input_keyhandler.c
  srcs/event/light_key_transformation.c
  srcs/event/object_transformaation.c
  srcs/event/sphere_key_transfromation.c
  srcs/interface/elements_interface1.c
  srcs/interface/template_interface.c
  srcs/interface/window_interface.c
  srcs/main.c
  srcs/obj/plane.c
  srcs/obj/scene.c
  srcs/parsing/parsing_input.c
  srcs/render.c
  srcs/setup.c
Labels: bug

#15 norm: mandatory
  Makefile
  files/around_object.rt
  files/object.rt
  includes/data.h
  includes/error.h
  includes/key.h
  includes/minirt.h
  includes/trans.h
  includes/utils.h
  srcs/camera.c
  srcs/debug/print_tdata.c
  srcs/debug/print_utils.c
  srcs/event/camera_key_transformation.c
  srcs/event/input_keyhandler.c
  srcs/event/object_transformation1.c
  srcs/event/object_transformation2.c
  srcs/exit.c
  srcs/interface/elements_interface1.c
  srcs/interface/elements_interface2.c
  srcs/interface/template_interface.c
  srcs/interface/template_interface1.c
  srcs/interface/template_interface2.c
  srcs/interface/window_interface.c
  srcs/light.c
  srcs/main.c
  srcs/obj/cone.c
  srcs/obj/cone1.c
  srcs/obj/cone2.c
  srcs/obj/cylinder.c
  srcs/obj/cylinder1.c
  srcs/obj/cylinder2.c
  srcs/obj/obj.c
  srcs/obj/plane.c
  srcs/obj/sphere.c
  srcs/parsing/parsing_input.c
  srcs/parsing/validate.c
  srcs/render.c
  srcs/setup.c
  srcs/transform/trans.c
  srcs/transform/trans_homo.c
  srcs/utils/converting_value.c
  srcs/utils/function_utils2.c
  srcs/utils/unit.c
Labels: norminette

#19 fix: rotated plane
  srcs/obj/plane.c
Labels: bug

#21 fixed #17 cylinder rotated
  files/object.rt
  srcs/obj/cylinder1.c
Labels: bug

#22 Closes #17 object rotation cone
  files/object.rt
  includes/data.h
  includes/minirt.h
  includes/mlx.h
  includes/trans.h
  includes/utils.h
  srcs/obj/cone1.c
  srcs/setup.c
  srcs/transform/trans.c
  srcs/utils/exit.c
Labels: bug

#24 add rotation objects with radian feature.
  files/around_object.rt
  files/basic.rt
  files/cone.rt
  files/cylinder.rt
  files/misconfig.rt
  files/muti_objects.rt
  files/object.rt
  files/plane.rt
  files/sample.rt
  files/sphere.rt
  includes/data.h
  srcs/event/input_keyhandler.c
  srcs/event/object_transformation1.c
  srcs/event/object_transformation2.c
  srcs/light.c
  srcs/obj/cone1.c
  srcs/obj/cylinder1.c
  srcs/obj/plane.c
  srcs/obj/sphere.c
  srcs/parsing/validate.c
  srcs/transform/trans.c
Labels: Feature

#34 added funtion rotation for each axis
  files/around_object.rt
  includes/data.h
  srcs/event/camera_key_transformation.c
  srcs/event/camera_rotation_x.c
  srcs/event/camera_rotation_y.c
  srcs/event/camera_rotation_z.c
  srcs/event/input_keyhandler.c
Labels: bug, enhancement

#38 Develop
  Makefile
  files/cone.rt
  files/cylinder.rt
  files/misconfig.rt
  files/multi_objects.rt
  files/plane.rt
  files/sphere.rt
  includes/data.h
  includes/minirt.h
  includes/utils.h
  srcs/event/camera_key_transformation.c
  srcs/event/camera_rotation_x.c
  srcs/event/camera_rotation_y.c
  srcs/event/camera_rotation_z.c
  srcs/event/input_keyhandler.c
  srcs/event/object_transformation1.c
  srcs/function_render.c
  srcs/interface/selection_interface.c
  srcs/interface/window_interface.c
  srcs/light.c
  srcs/light2.c
  srcs/main.c
  srcs/materials/checker.c
  srcs/materials/material.c
  srcs/materials/trans_txtr.c
  srcs/obj/bonus_argument.c
  srcs/obj/cone1.c
  srcs/obj/cylinder1.c
  srcs/obj/obj.c
  srcs/obj/plane.c
  srcs/obj/sphere.c
  srcs/parsing/parsing_input.c
  srcs/render.c
  srcs/utils/color.c
  srcs/utils/exit.c
  srcs/utils/function_utils2.c
Labels: Feature
